### ISSUE TITLE
Not able to read .ini file in another folder

### ISSUE THREAD

**Issue by blurryrox** [Kulothungan16/kvhot#2]
My project folder is like this:

```
Proj/
    - venv/ <--- kvhot inside
    - app/ 
        - main.,py
        - data/
            - cfg.ini
```

So i use `configparser `to read setting in `app/data/cfg.ini`
but it seems that it couldn't find the section it is supposed to read from.
` configparser.NoSectionError: No section: 'auth'`
running main.py directly does not have this problem
My editor is pycharm

**Comment by kulothunganug** [comment]
Can you present a detailed context of the issue?
What command you ran and in which folder?

> Apologies for not responding to the issue for months...

**Comment by kulothunganug** [comment]
Closing because of not having enough details/no response about the issue
