### ISSUE TITLE
Unable to pass arguments to main.py using Kvhot

### ISSUE THREAD

**Issue by Bobspadger** [Kulothungan16/kvhot#3]
First of all - thank-you for the incredibly useful application!.

We have a use case where our application requires some arguments passed to our `main.py` file (example main.py /data --log-level=debug` and are currently unable to do this with the system in its current form.

i'm happy to do the work to enable this, but before commencing, how would you prefer this was implemented? (additional parameters, set environment variables outside of kvhot etc)

If you are happy for this to be a feature please let me know and I'll implement this.

Thanks in advance :)

**Comment by Bobspadger** [comment]
See #4 for my suggested solution

**Comment by kulothunganug** [comment]
I didn’t expected a feature of passing arguments for a Kivy app, but it’s a nice addition. I’ll review the pull request soon.

Thanks!
